# Configurações de build
[build]
  # Diretório a partir do qual começar a build
  base = ""

  # Diretório que contém a saída da build
  publish = "public"

  # Diretório das funções Netlify (se houver)
  functions = "functions"

  # Comando para build do projeto
  command = "npm run build"

# Configurações de deploy
[context.production.environment]
  # Variáveis de ambiente específicas para deploy em produção (ex.: credenciais do Azure)
  NODE_ENV = "production"
  DB_CONNECTION_STRING = "fatecserver.database.windows.net"

[context.deploy-preview]
  # Variáveis de ambiente específicas para pré-visualizações de deploy
  NODE_ENV = "development"
  DB_CONNECTION_STRING = "fatecserver.database.windows.net"

# Cabeçalhos HTTP
[[headers]]
  # Define quais caminhos este bloco específico [[headers]] irá cobrir.
  for = "/*"

  [headers.values]
    # Configurações de cache do Netlify
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  # Redirecionamentos para single-page applications (SPA) no Netlify
  from = "/*"
  to = "/index.html"
  status = 200
